# DO NOT create top level (global) keys like env, arch, os, compiler.
# The top level/global keys invoke [unwanted] matrix expansion. Also
# see https://stackoverflow.com/q/58473000/608639 and
# https://docs.travis-ci.com/user/reference/overview/ and
# https://docs.travis-ci.com/user/multi-cpu-architectures and
# https://github.com/travis-ci/travis-yml/blob/master/schema.json.

language: cpp
dist: bionic
sudo: required

git:
  depth: 2

# Use jobs rather than matrix since we are precisely
# specifiying our test cases. Do not move any of the
# keys (env, os, arch, compiler, etc) into global.
# Putting them in global invokes the matrix expansion.
jobs:
  include:
    - os: linux
      name: Linux, amd64, GCC
      arch: amd64
      compiler: gcc
      dist: xenial
    - os: linux
      name: Linux, amd64, Clang
      arch: amd64
      compiler: clang
      dist: xenial
    - os: linux
      name: Linux, amd64, GCC
      arch: amd64
      compiler: gcc
      dist: bionic
    - os: linux
      name: Linux, amd64, Clang
      arch: amd64
      compiler: clang
      dist: bionic
    - os: linux
      name: Linux, arm64, GCC
      arch: arm64
      compiler: gcc
      dist: bionic
    - os: linux
      name: Linux, arm64, Clang
      arch: arm64
      compiler: clang
      dist: bionic
    - os: linux
      name: Linux, ppc64le, GCC
      arch: ppc64le
      compiler: gcc
      dist: bionic
    - os: linux
      name: Linux, ppc64le, Clang
      arch: ppc64le
      compiler: clang
      dist: bionic
    - os: osx
      osx_image: xcode11.2
      name: OS X 10.14, XCode 11.2
      arch: amd64
    - os: osx
      osx_image: xcode9.4
      name: OS X 10.13, XCode 9.4
      arch: amd64
    - os: osx
      osx_image: xcode6.4
      name: OS X 10.10, XCode 6.4
      arch: amd64

  allow_failures:
    # Clang 7.1 and below will fail on PPC64 due to
    # https://bugs.llvm.org/show_bug.cgi?id=39704
    - os: linux
      arch: ppc64le
      compiler: gcc
    - os: linux
      arch: ppc64le
      compiler: clang

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A145
      sudo apt-get update
      sudo apt-get -y install autoconf automake libtool
    fi

    # Let travis clone cryptopp-autotools, clone cryptopp
    # copy cryptopp-autotools to cryptopp, and then run
    # the test script.
  - |
    cd ..
    git clone https://github.com/weidai11/cryptopp.git
    cp cryptopp-autotools/*.* cryptopp/
    cd cryptopp
    cp TestScripts/cryptest-autotools.sh .

script:
  - |    
    bash cryptest-autotools.sh

# Whitelist branches to avoid testing feature branches twice
branches:
  only:
    - master
    - /\/ci$/

notifications:
  email:
    recipients:
      - cryptopp-build@googlegroups.com
    on_success: always # default: change
    on_failure: always # default: always
